version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    user: ${CURRENT_UID}
  web:
    build: .
    user: ${CURRENT_UID}
    volumes:
      - .:/myapp
    ports:
      - "3000-3001:3000-3001"
    depends_on:
      - db
